# SITE CONFIGURATION
title: ML for Accelerator Physics # your site title
author: Kilean (Kyung Ryun) Hwang # You :P
description: > # Meta description of Homepage
  Experiments on machine learning for accelerator physics application
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kilean20.github.io/" 

# SEO PLUGIN
social:
  name: Kilean Hwang
  links:
    - https://www.linkedin.com/in/kilean20/
    - https://github.com/kilean20

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Contact', link: '/contact'}
#  - {name: 'About me', link: '/about'}

tagline: >
  Experiments on machine learning for accelerator physics application

hero_img: posts/bison.jpg # Main background image: use the path from /assets/img/ 

email: kilean20@gmail.com # email for form submission

github_username:  kilean20 # replace with your_github_username or comment to remove link from footer
linkedin_username: kilean20

disqus:
  shortname: kilean20 # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
